  // import Catagorie1 from "../catagorie1/catagorie";
  // import Cat2 from "../catagorie1/Cat2";
  // import Cat3 from "../catagorie1/cat3";
  //   let localdata=JSON.parse(localStorage.getItem("buyurtma_page"))
  //   const roms=[
  //     {
  //       id:1,
  //       typeID:1,
  //       window:Cat2
  //     },
  //     {
  //       id:2,
  //       typeID:1,
  //       window:Cat3
  //     },
  //     {
  //       id:3,
  //       typeID:1,
  //       window:Cat3
  //     },
  //     {
  //       id:4,
  //       typeID:1,
  //       window:Cat2
  //     },
  //     {
  //       id:5,
  //       typeID:2,
  //       window:Catagorie1
  //     },
  //     {
  //       id:6,
  //       typeID:2,
  //       window:Catagorie1
  //     },
  //     {
  //       id:7,
  //       typeID:2,
  //       window:Catagorie1
  //     },
  //     {
  //       id:8,
  //       typeID:2,
  //       window:Catagorie1
  //     },
  //     {
  //       id:9,
  //       typeID:2,
  //       window:Catagorie1
  //     },
  //     {
  //       id:10,
  //       typeID:2,
  //       window:Catagorie1
  //     },
  //     {
  //       id:11,
  //       typeID:3,
  //       window:Catagorie1
  //     },
  //     {
  //       id:12,
  //       typeID:3,
  //       window:Catagorie1
  //     },
  //     {
  //       id:13,
  //       typeID:3,
  //       window:Catagorie1
  //     },
  //     {
  //       id:14,
  //       typeID:3,
  //       window:Catagorie1
  //     },
  //     {
  //       id:15,
  //       typeID:3,
  //       window:Catagorie1
  //     },
  //     {
  //       id:16,
  //       typeID:3,
  //       window:Catagorie1
  //     },
  //     {
  //       id:17,
  //       typeID:3,
  //       window:Catagorie1
  //     },
  //     {
  //       id:18,
  //       typeID:3,
  //       window:Catagorie1
  //     }
  //   ]
  //   console.log(localdata)
  //  let ExportWindow=roms[localdata.category];
  //  console.log(ExportWindow.window)
  //  export default ExportWindow